### ISSUE TITLE
Fail to Run JUnit 5 Tests of Nested Class

### ISSUE THREAD

**Issue by luoos** [TestingResearchIllinois/testrunner#8]
The [JUnit 5 Executor](https://github.com/TestingResearchIllinois/testrunner/blob/f528008de25b0b97263f97d5f373eedac327ef1a/testrunner-running/src/main/scala/edu/illinois/cs/testrunner/execution/JUnit5TestExecutor.java#L16) fails to run tests of nested classes. For example, [StringDistancesTest.CreateStringDistances#damerauLevenshtein](https://github.com/mpkorstanje/simmetrics/blob/f0458e3c470d6fdbd102a22a2ede033c1fd4d103/simmetrics-core/src/test/java/org/simmetrics/metrics/StringDistancesTest.java#L254)

Exception:

```
ERROR (WRITE_ERROR_STDOUT_THROWABLE): com.github.mpkorstanje:simmetrics-core:4.1.2-SNAPSHOT
java.lang.RuntimeException: Set of executed tests is not equal to test list that should have been executed (53 tests executed, 192 tests expected). Missing tests are: Set(org.simmetrics.metrics.StringDistancesTest.CreateStringDistances#longestCommonSubsequence, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetric, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithFilterAndTransform02, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithFilterAndTransform01, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#smithWatermanGotoh, org.simmetrics.builders.StringMetricsTest.CreateForSet#shouldReturnForSetWithSimplifier, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistance02, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithSimplifier01WithCache, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#needlemanWunch, org.simmetrics.metrics.HammingDistanceTest.DistanceString#shouldThrowForDifferentLength, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnForSetWithSimplifier, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#longestCommonSubsequence, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithFilterAndTransform02, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithSimplifier01, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnForListWithSimplifier, org.simmetrics.metrics.StringDistancesTest.CreateStringDistances#hammingDistance, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithTransform, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testStringMetric01, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testStringDistanceWithSimplifer02WithCache, org.simmetrics.builders.StringDistancesTest.CreateForMultiset#shouldReturnForSet, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithFilter, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetric01WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithFilterAndTransform01, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#smithWaterman, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testStringMetricWithSimplifier02, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetric, org.simmetrics.metrics.DamerauLevenshteinTest.OutofBounds#shouldThrowForDeleteCostOnBound, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithSimplifier01, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistance, org.simmetrics.builders.StringDistancesTest.CreateForList#shouldReturnForListWithSimplifier, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithSimplifier01WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testStringMetricWithSimplifier01WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetric02, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistance02, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnForStringWithChainedSimplifiers, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetric, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithSimplifier02WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithSimplifier02WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testStringDistanceWithSimplifier01WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetric02WithCache, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnForSetWithChainedSimplifiers, org.simmetrics.metrics.StringDistancesTest.CreateStringDistances#longestCommonSubstring, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnForStringWithSimplifier, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithFilter, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithSimplifier02, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetric02WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetric02WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistance02, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testStringMetricWithSimplifer02WithCache, org.simmetrics.simplifiers.SimplifiersTest.ShouldThrowFor#chainWithNull, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithFilterAndTransform02, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithFilterAndTransform01, org.simmetrics.metrics.StringDistancesTest.Utilities#blockMetric, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithTransform, org.simmetrics.builders.StringMetricsTest.CreateForList#shouldReturnForListWithSimplifier, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnSame, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithFilterAndTransform02, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithSimplifier02WithCache, org.simmetrics.simplifiers.SimplifiersTest.ShouldThrowFor#chainWithListContainingNull, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithFilter, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithSimplifier02, org.simmetrics.builders.StringDistancesTest.CreateForList#shouldReturnForList, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistance02WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithTransform, org.simmetrics.metrics.DamerauLevenshteinTest.OutofBounds#shouldThrowForDeleteCostBelowBound, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#jaro, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithFilterAndTransform02, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithFilterAndTransform01, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnForSetWithChainedSimplifiers, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithTransform, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithSimplifier02, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistance02WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistance, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testStringDistanceWithSimplifier01, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithSimplifier01WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithSimplifier01, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnForStringWithSimplifier, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testStringMetricWithSimplifier01, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnSame, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithFilter, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistance01WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetric01WithCache, org.simmetrics.metrics.DamerauLevenshteinTest.OutofBounds#shouldThrowForTransposeCostBelowBound, org.simmetrics.builders.StringMetricsTest.CreateForMultiset#shouldReturnForSetWithSimplifier, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistanceWithSimplifier01, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithFilterAndTransform02, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnForListWithChainedSimplifiers, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithFilterAndTransform01, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithFilterAndTransform01, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistance01WithCache, org.simmetrics.builders.StringDistancesTest.CreateForSet#shouldReturnForSetWithSimplifier, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetric02, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithSimplifier02WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithSimplifier01, org.simmetrics.builders.StringMetricsTest.CreateForSet#shouldReturnForSet, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithFilter, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithSimplifier01, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistance02WithCache, org.simmetrics.metrics.StringDistancesTest.CreateStringDistances#jaroWinkler, org.simmetrics.metrics.DamerauLevenshteinTest.OutofBounds#shouldThrowForSubstituteCostBelowBound, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithSimplifier01WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testSetDistance, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithSimplifier01WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithFilter, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testStringDistance01, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetric01WithCache, org.simmetrics.simplifiers.SimplifiersTest.ShouldThrowFor#chainWithSingletonList, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetricWithSimplifier02, org.simmetrics.builders.StringDistancesTest.CreateForMultiset#shouldReturnForSetWithSimplifier, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithSimplifier01WithCache, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testSetMetric02, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnForListWithChainedSimplifiers, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistance01WithCache, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testMultisetDistanceWithTransform, org.simmetrics.builders.StringMetricsTest.CreateForList#shouldReturnForList, org.simmetrics.metrics.StringMetricsTest.Utilities#blockDistance, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#longestCommonSubstring, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnForListWithSimplifier, org.simmetrics.builders.StringDistancesTest.CreateForSet#shouldReturnForSet, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testStringDistanceWithSimplifier02, org.simmetrics.simplifiers.SimplifiersTest.ShouldThrowFor#chainWithNullInVarArg, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnForStringWithChainedSimplifiers, org.simmetrics.builders.StringDistanceBuilderTest.StringDistanceBuilderChainTest#testListDistanceWithSimplifier02, org.simmetrics.builders.StringMetricsTest.CreateForMultiset#shouldReturnForSet, org.simmetrics.metrics.StringDistancesTest.CreateStringDistances#levenshtein, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithSimplifier02WithCache, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#damerauLevenshtein, org.simmetrics.simplifiers.SimplifiersTest.ShouldThrowFor#chainWithSingle, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithTransform, org.simmetrics.metrics.HammingDistanceTest.DistanceList#shouldThrowForDifferentLength, org.simmetrics.builders.StringDistancesTest.Create#shouldReturnForString, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testListMetricWithSimplifier02, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#levenshtein, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnForString, org.simmetrics.metrics.StringMetricsTest.CreateStringMetrics#jaroWinkler, org.simmetrics.metrics.StringDistancesTest.CreateStringDistances#jaro, org.simmetrics.builders.StringMetricsTest.Create#shouldReturnForSetWithSimplifier, org.simmetrics.builders.StringMetricBuilderTest.StringMetricBuilderChainTest#testMultisetMetricWithSimplifier02WithCache, org.simmetrics.metrics.StringDistancesTest.CreateStringDistances#damerauLevenshtein)
	at edu.illinois.cs.testrunner.runner.SmartRunner.$anonfun$run$1(SmartRunner.scala:40)
	at scala.util.Success.flatMap(Try.scala:247)
	at edu.illinois.cs.testrunner.runner.SmartRunner.run(SmartRunner.scala:33)
	at edu.illinois.cs.testrunner.runner.Runner.runList(Runner.scala:28)
	at edu.illinois.cs.testrunner.runner.Runner.runList$(Runner.scala:27)
	at edu.illinois.cs.testrunner.runner.SmartRunner.runList(SmartRunner.scala:21)
	at edu.illinois.cs.dt.tools.detection.DetectorUtil.originalResults(DetectorUtil.java:32)
	at edu.illinois.cs.dt.tools.detection.detectors.RandomDetector.<init>(RandomDetector.java:26)
	at edu.illinois.cs.dt.tools.detection.detectors.DetectorFactory.makeDetector(DetectorFactory.java:19)
	at edu.illinois.cs.dt.tools.detection.DetectorPlugin.detectorExecute(DetectorPlugin.java:239)
	at edu.illinois.cs.dt.tools.detection.DetectorPlugin.lambda$execute$5(DetectorPlugin.java:201)
	at edu.illinois.cs.dt.tools.utility.ErrorLogger.runAndLogError(ErrorLogger.java:39)
	at edu.illinois.cs.dt.tools.detection.DetectorPlugin.execute(DetectorPlugin.java:201)
```

**Comment by luoos** [comment]
Fixed with https://github.com/TestingResearchIllinois/testrunner/pull/13
